### ISSUE TITLE
Is it possible to have %hnum is able to read point instead of comma separated numbers?

### ISSUE THREAD

**Issue by RamonaTigier** [EDDiscovery/ActionLanguage#4]
Is it possible to have %hnum is able to read point instead of comma separated numbers?
As in German there is point instead of comma separation and comma instead of point floats.
Many thanks.

**Comment by robbyxp1** [comment]
The action code uses Invariant culture for its operation to make sure it works across the world.

So all numbers end up in 10.20 format.

But your right, it would be nice to be able to tell it to use the current culture when converting numbers for printing/reading

Applicable functions would be:

eval (not the other ones abs int etc as they are for programming)
hnum

This will get done at some point, not quite yet.

**Comment by RamonaTigier** [comment]
Hi, 
thanks for the comeback.

The issue I'm featuring is that sometimes - not every time - the credits were read as: 
"1 o'clock 234 million credits"
instead of 
"1 million 234 credits"
when using VoicePack17 - facing this since using VoicePack12.

Maybe a issue in the VoicePack when using not english cultures?

Many thanks.
